### ISSUE TITLE
Chapter 11.2.3: Can not install the logger

### ISSUE THREAD

**Issue by haglo** [fmarchioni/wildfly-admin-guide#1]
When i add with the following cli-Command
`
/subsystem=logging/custom-handler=DBLogHandler/:add(class=com.mastertheboss.JdbcLogger,module=org.logger.mysql,level=INFO,formatter="%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%E%n", properties={"driverClassName" => "com.mysql.jdbc.Driver","jdbcUrl" => "jdbc:mysql://localhost:3306/pilgerdb","username"=> "pilgeruser","secret" => "jdbc:mysql://localhost:3306/pilgerdb"})

`
I get the following error:

`
ername"=> "pilgeruser","secret" => "jdbc:mysql://localhost:3306/pilgerdb"}) => "com.mysql.jdbc.Driver","jdbcUrl" => "jdbc:mysql://localhost:3306/pilgerdb","us
'[B[B/subsystem=logging/custom-handler=DBLogHandler/:add(class=com.mastertheboss.JdbcLogger,module=org.logger.mysql,level=INFO,formatter="%d{HH:mm:ss,SSS}' is not a valid operation name.

`

**Comment by fmarchioni** [comment]
There's an error in the original script (the password field). 
Besides it, I was able to install the DBLogger as follows:
```
[standalone@localhost:9990 / #] /subsystem=logging/custom-handler=DBLogHandler/:add(class=com.mastertheboss.JdbcLogger,module=org.logger.mysql,level=INFO,formatter="%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%E%n", properties={"driverClassName" =>"com.mysql.jdbc.Driver","jdbcUrl" => "jdbc:mysql://localhost:3306/mysqlschema","username" => "jboss","password" => "jboss"})
[standalone@localhost:9990 / #] /subsystem=logging/root-logger=ROOT:add-handler(name=DBLogHandler)
[standalone@localhost:9990 / #] run-batch 
The batch executed successfully
```

Check that the related dependency (module com.mysql) has been already installed successfully.
Thanks
Francesco
