### ISSUE TITLE
Chapter: 11.6.2: Not working

### ISSUE THREAD

**Issue by haglo** [fmarchioni/wildfly-admin-guide#2]
Hello, the following commands are not working:

`
curl --digest -L -D - http://127.0.0.1:9990/management?useStreamAsResponse --header "ContentType: application/json" -u admin:secret -d '{"operation":"read-attribute","address":[{"subsystem":"logging"},{"log-file":"server.log"}],"name":"stream"}'
`
The error is: <html><head><title>Error</title></head><body>415 - Unsupported Media Type</body></html>

**Comment by fmarchioni** [comment]
Hi Hans, thanks for your feedback.
Apologizes for the delay, I was able to run the above command with:
`curl --digest -L -D - http://127.0.0.1:9990/management?useStreamAsResponse --header "Content-Type: application/json" -u admin:Password1! -d '{"operation":"read-attribute","address":[{"subsystem":"logging"},{"log-file":"server.log"}],"name":"stream"}'`

(replace user/password with your management password).
I have fixed the above in the ebook as well.
